### ISSUE TITLE
Two Sum

### ISSUE THREAD

**Issue by jichuangwei** [zzxboy1/leetcode#1]
console.log(twoSum([2,2,4],6)) try

**Comment by zzxboy1** [comment]
Thank you for remind me. u mean the answer should be [0, 2]? But according to the description,  [1,2] is ok I think.

**Comment by jichuangwei** [comment]
but 

![](https://s1.ax1x.com/2018/04/12/CEkuOH.png)

**Comment by zzxboy1** [comment]
thanks a lot
